const properties = [
    {
      id: 1,
      title: "Modern Waterfront Villa",
      location: "Malibu, California",
      price: 4500000,
      type: "Villa",
      status: "For Sale",
      badge: "Featured",
      bedrooms: 5,
      bathrooms: 4,
      size: 4200,
      description: "A breathtaking waterfront villa with panoramic ocean views and a private infinity pool.",
      feature: "Ocean View",
      image: "https://images.unsplash.com/photo-1613977257363-707ba9348227?q=80&w=2070&auto=format&fit=crop"
    },
    {
      id: 2,
      title: "Downtown Luxury Penthouse",
      location: "Manhattan, New York",
      price: 8900000,
      type: "Penthouse",
      status: "For Sale",
      badge: "Exclusive",
      bedrooms: 4,
      bathrooms: 3,
      size: 3800,
      description: "An iconic penthouse perched above Manhattan with floor to ceiling windows and city skyline views.",
      feature: "City Skyline View",
      image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=2053&auto=format&fit=crop"
    },
    {
      id: 3,
      title: "Private Hillside Mansion",
      location: "Beverly Hills, California",
      price: 12000000,
      type: "Mansion",
      status: "For Sale",
      badge: "New Listing",
      bedrooms: 7,
      bathrooms: 6,
      size: 8500,
      description: "A grand hillside mansion offering unrivalled privacy, a home theatre, and resort style amenities.",
      feature: "Private Pool",
      image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2070&auto=format&fit=crop"
    },
    {
      id: 4,
      title: "Elegant Garden Apartment",
      location: "Kensington, London",
      price: 12000,
      type: "Apartment",
      status: "For Rent",
      badge: "Featured",
      bedrooms: 3,
      bathrooms: 2,
      size: 1800,
      description: "A beautifully appointed apartment in the heart of Kensington with a private garden and concierge service.",
      feature: "Private Garden",
      image: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?q=80&w=2070&auto=format&fit=crop"
    },
    {
      id: 5,
      title: "Beachfront Smart Home",
      location: "Miami Beach, Florida",
      price: 6750000,
      type: "Villa",
      status: "For Sale",
      badge: "Exclusive",
      bedrooms: 5,
      bathrooms: 5,
      size: 5100,
      description: "A cutting edge smart home sitting directly on Miami Beach with automated systems and a private dock.",
      feature: "Smart Home",
      image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=2070&auto=format&fit=crop"
    },
    {
      id: 6,
      title: "Alpine Luxury Chalet",
      location: "Verbier, Switzerland",
      price: 9500,
      type: "Chalet",
      status: "For Rent",
      badge: "New Listing",
      bedrooms: 6,
      bathrooms: 4,
      size: 4600,
      description: "An extraordinary alpine chalet with ski in ski out access, a spa, and breathtaking mountain views.",
      feature: "Ski In Ski Out",
      image: "https://images.unsplash.com/photo-1601918774946-25832a4be0d6?q=80&w=2069&auto=format&fit=crop"
    }
  ];